In [1]:
lst = [1, 2, 3, 4, 5]

In [3]:
lst.append(6)

In [4]:
lst.extend([7, 8])

In [5]:
lst

[1, 2, 3, 4, 5, 6, 7, 8]

In [6]:
lst.insert(2, 'a')

In [7]:
lst

[1, 2, 'a', 3, 4, 5, 6, 7, 8]

In [8]:
lst.remove(2)

In [9]:
lst

[1, 'a', 3, 4, 5, 6, 7, 8]

In [10]:
lst.pop()

8

In [11]:
lst

[1, 'a', 3, 4, 5, 6, 7]

In [13]:
lst.pop(2)

3

In [14]:
lst.clear()

In [15]:
lst

[]

In [16]:
lst = [1, 2, 'x', 3, 4]

In [17]:
lst.index('x')

2

In [18]:
lst.append(2)

In [19]:
lst

[1, 2, 'x', 3, 4, 2]

In [20]:
lst.count(2)

2

In [21]:
lst.sort()

TypeError: '<' not supported between instances of 'str' and 'int'

In [22]:
lst.remove('x')

In [23]:
lst.sort()

In [24]:
lst

[1, 2, 2, 3, 4]

In [25]:
lst.reverse()

In [26]:
lst

[4, 3, 2, 2, 1]

In [27]:
new_lst = lst.copy()

In [28]:
new_lst

[4, 3, 2, 2, 1]

In [37]:
my_tuple = (1, 2, 2, 3, 'Shivam')

In [38]:
my_tuple.count(2)

2

In [39]:
my_tuple.index('Shivam')

4

In [40]:
my_tuple[1]

2

In [41]:
tup = (1, 1)

In [44]:
lst = [1, 2, 3, 4, 5]

In [45]:
lst

[1, 2, 3, 4, 5]

In [48]:
lst.append(2)

In [49]:
lst

[1, 2, 3, 4, 5, 2, 2]

In [50]:
lst.extend([3, 'x'])

In [51]:
lst

[1, 2, 3, 4, 5, 2, 2, 3, 'x']

In [52]:
lst.insert(1, 'One on the left')

In [53]:
lst

[1, 'One on the left', 2, 3, 4, 5, 2, 2, 3, 'x']

In [54]:
lst.remove(2)

In [55]:
lst

[1, 'One on the left', 3, 4, 5, 2, 2, 3, 'x']

In [56]:
lst.pop('x')

TypeError: 'str' object cannot be interpreted as an integer

In [57]:
lst.pop()

'x'

In [58]:
lst

[1, 'One on the left', 3, 4, 5, 2, 2, 3]

In [59]:
lst.pop(5)

2

In [60]:
lst

[1, 'One on the left', 3, 4, 5, 2, 3]

In [62]:
x = lst.copy()

In [63]:
x

[1, 'One on the left', 3, 4, 5, 2, 3]

In [64]:
x.clear()

In [65]:
x

[]

In [66]:
lst.index(2)

5

In [67]:
lst.count(5)

1

In [68]:
lst.count(3)

2

In [69]:
lst.sort()

TypeError: '<' not supported between instances of 'str' and 'int'

In [70]:
lst.reverse()

In [71]:
lst

[3, 2, 5, 4, 3, 'One on the left', 1]

In [72]:
x = lst.copy()

In [73]:
x

[3, 2, 5, 4, 3, 'One on the left', 1]

2. Tuple is ordered immutable collections of items. can contain elements of different types.

In [74]:
# Methods
tup = (1, 2, 3, 'apple')

In [76]:
type(tup)

tuple

In [77]:
tup.count(1)

1

In [78]:
tup.index('apple')

3

SET : Set is an unordered mutable collection of distinct items. 

In [80]:
st = {1, 2, 3, 'apple'}

In [81]:
st

{1, 2, 3, 'apple'}

In [83]:
st.add('x')

In [84]:
st

{1, 2, 3, 'apple', 'x'}

In [85]:
st.add(2)

In [86]:
st

{1, 2, 3, 'apple', 'x'}

In [87]:
st.remove(2)

In [88]:
st

{1, 3, 'apple', 'x'}

In [89]:
st.add([1, 2])

TypeError: unhashable type: 'list'

In [90]:
st.add((1, 2))

In [91]:
st

{(1, 2), 1, 3, 'apple', 'x'}

4. Numpy array : 
Definition: A NumPy array is a powerful N-dimensional array object which is in the form of rows and columns. It provides a high-performance multidimensional array object and tools for working with these arrays.

In [92]:
import numpy as np

In [93]:
arr = np.array([1, 2, 3, 4])

In [94]:
arr

array([1, 2, 3, 4])

In [95]:
type(arr)

numpy.ndarray

In [96]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [98]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [103]:
zeros_arr = np.zeros((3, 3))

In [104]:
zeros_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [105]:
zeros_arr = np.ones((3, 3))

In [106]:
zeros_arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [107]:
arr3 = np.arange(0, 10, 2)

In [108]:
arr3

array([0, 2, 4, 6, 8])

In [109]:
linspace_arr = np.linspace(0, 1, 5)

In [110]:
linspace_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])


5. DataFrame (pandas)
Dataframe is a 2D labeled data structure with columns of different types. It is similar to a table in a database or a dataframe in R.
Pandas library is used to create Datafrae.


In [111]:
import pandas as pd

In [125]:
# Creating a DataFrame from a dictionary
data = {
    'Name' : ['John', 'Jane', 'Alice'],
    'Age' : [23, 27, 30],
    'City' : ['New York', 'Paris', 'London']
}

In [126]:
data

{'Name': ['John', 'Jane', 'Alice'],
 'Age': [23, 27, 30],
 'City': ['New York', 'Paris', 'London']}

In [127]:
df = pd.DataFrame(data)

In [116]:
df

Name  Age      City
0   John   23  New York
1   Jane   27     Paris
2  Alice   30    London

In [117]:
# Creating a DataFrame from a NumPy array
array_data = np.array([[1, 2, 3], [4, 5, 6]])

In [118]:
array_data

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
df = pd.DataFrame(array_data, columns = ['A', 'B', 'C'])

In [122]:
df

A  B  C
0  1  2  3
1  4  5  6

In [ ]:
# Creating a DataFrame from a CSV file
df_from_csv = pd.read_csv()

In [123]:
# Creating an empty dataframe
empty_df = pd.DataFrame()

In [124]:
empty_df

Empty DataFrame
Columns: []
Index: []

In [128]:
df

Name  Age      City
0   John   23  New York
1   Jane   27     Paris
2  Alice   30    London

In [129]:
df['Name']

0     John
1     Jane
2    Alice
Name: Name, dtype: object

In [130]:
df['Age']

0    23
1    27
2    30
Name: Age, dtype: int64

In [131]:
df['City']

0    New York
1       Paris
2      London
Name: City, dtype: object

In [135]:
df

Name  Age      City
0   John   23  New York
1   Jane   27     Paris
2  Alice   30    London

In [134]:
df.loc[0]

Name        John
Age           23
City    New York
Name: 0, dtype: object

In [138]:
df.loc[1]

Name     Jane
Age        27
City    Paris
Name: 1, dtype: object

In [141]:
df.iloc[2]

Name     Alice
Age         30
City    London
Name: 2, dtype: object

In [142]:
df['Country'] = ['USA', 'France', 'UK']

In [143]:
df

Name  Age      City Country
0   John   23  New York     USA
1   Jane   27     Paris  France
2  Alice   30    London      UK

In [145]:
print(df.describe())

             Age
count   3.000000
mean   26.666667
std     3.511885
min    23.000000
25%    25.000000
50%    27.000000
75%    28.500000
max    30.000000


In [146]:
df['Salary'] = [10000, 20000, 30000]

In [147]:
df

Name  Age      City Country  Salary
0   John   23  New York     USA   10000
1   Jane   27     Paris  France   20000
2  Alice   30    London      UK   30000

In [148]:
df.describe()

Age   Salary
count   3.000000      3.0
mean   26.666667  20000.0
std     3.511885  10000.0
min    23.000000  10000.0
25%    25.000000  15000.0
50%    27.000000  20000.0
75%    28.500000  25000.0
max    30.000000  30000.0

In [151]:
df

Name  Age      City Country  Salary
0   John   23  New York     USA   10000
1   Jane   27     Paris  France   20000
2  Alice   30    London      UK   30000

Difference between loc and iloc

loc

In [150]:
print(df.loc[: , 'Name']) 

0     John
1     Jane
2    Alice
Name: Name, dtype: object


In [153]:
print(df.loc[:, 'City'])

0    New York
1       Paris
2      London
Name: City, dtype: object


In [154]:
print(df.loc[0])

Name           John
Age              23
City       New York
Country         USA
Salary        10000
Name: 0, dtype: object


In [160]:
print(df.loc[2, ['City','Salary']])

City      London
Salary     30000
Name: 2, dtype: object


iloc

In [162]:
df

Name  Age      City Country  Salary
0   John   23  New York     USA   10000
1   Jane   27     Paris  France   20000
2  Alice   30    London      UK   30000

In [164]:
df.iloc[1,:]

Name         Jane
Age            27
City        Paris
Country    France
Salary      20000
Name: 1, dtype: object

In [166]:
df.iloc[1:, 3:]

Country  Salary
1  France   20000
2      UK   30000

FUNCTIONS OF NUMPY

1. Creating arrays

In [195]:
#1D
a = np.array([1, 2, 3])

In [168]:
a

array([1, 2, 3])

In [193]:
#2D
b = np.array([[1, 2], [3, 4]])

In [171]:
print(b)

[[1 2]
 [3 4]]


2. Zeros, ones, and empty

In [175]:
c = np.zeros((2,3))

In [176]:
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [177]:
d = np.ones((2, 3))

In [178]:
d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [182]:
e = np.empty((2, 3))

In [183]:
print(e)

[[1. 1. 1.]
 [1. 1. 1.]]


3. Arange and linspace

arange gives all element 

In [196]:
# Arange and linspace
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [197]:
# linspace gives equal distribution
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

3. Array Manipulation

In [198]:
a = np.array([1, 2, 3, 4, 5, 6])

In [199]:
a

array([1, 2, 3, 4, 5, 6])

In [200]:
a.shape

(6,)

In [203]:
# 1. Reshape
a.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [204]:
a.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [211]:
# 2. Concatenate
a = np.array([1, 2])
b = np.array([3, 4])
x = np.array([5, 6])
c = np.concatenate((a, b, x))

In [212]:
c

array([1, 2, 3, 4, 5, 6])

In [214]:
c.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [215]:
# 3. Transpose
a = np.array([[1, 2, 3], [4, 5, 6]])

In [217]:
x = a.T

In [218]:
x

array([[1, 4],
       [2, 5],
       [3, 6]])

In [219]:
a

array([[1, 2, 3],
       [4, 5, 6]])

Basic Operations

In [220]:
# 1. Element-wise operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [221]:
c = a + b

In [222]:
c

array([5, 7, 9])

In [227]:
c = a * b

In [228]:
c = a - b

In [229]:
c

array([-3, -3, -3])

In [230]:
# 2. Dot product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [231]:
dot_product = np.dot(a, b)

In [232]:
dot_product

32

In [234]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [242]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [243]:
b = np.array([[7, 8, 9], [10, 11, 12]])

In [250]:
b = b.reshape(3, 2)

In [251]:
x = np.dot(a, b)

In [252]:
x

array([[ 58,  64],
       [139, 154]])

In [253]:
# 3. Universal functions (ufuncs) like sqrt and exp
a = np.array([1, 2, 3])

In [254]:
a

array([1, 2, 3])

In [255]:
b = np.sqrt(a)

In [256]:
b

array([1.        , 1.41421356, 1.73205081])

In [257]:
c = np.exp(a)

In [258]:
c

array([ 2.71828183,  7.3890561 , 20.08553692])

Statistical Functions

In [261]:
# 1. Basic statistics
a = np.array([1, 2, 3, 4, 5])

In [263]:
mean = np.mean(a)
print(mean)

3.0


In [268]:
median = np.median(a)
print(median)

3.0


In [271]:
std = np.std(a)
print(std)

1.4142135623730951


In [272]:
# 2. Sum and product
a = np.array([1, 2, 3, 4, 5])

In [273]:
s = np.sum(a)
print(s)

15


In [274]:
p = np.prod(a)
print(p)

120


Indexing and Slicing

In [275]:
# 1. Indexing
a = np.array([1, 2, 3, 4, 5])

3

In [276]:
a[2]

3

In [280]:
# 2. Slicing
print(a[2:4])

[3 4]


Linear Algebra

In [286]:
# 1. Matrix multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.matmul(a, b)

In [287]:
c

array([[19, 22],
       [43, 50]])

In [288]:
x = np.dot(a, b)

In [289]:
x

array([[19, 22],
       [43, 50]])

In [292]:
# 2. Determinant and inverse
a = np.array([[1, 2], [3, 4]])
det = np.linalg.det(a)
inv = np.linalg.inv(a)

In [291]:
det

-2.0000000000000004

In [293]:
inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [294]:
I = np.dot(a, inv)

In [295]:
I

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

Random Numbers

In [300]:
# 1. Random numbers
# Array of random numbers between 0 and 1
random_array = np.random.rand(3, 4)

In [301]:
random_array

array([[0.11052474, 0.54392684, 0.56393039, 0.7593671 ],
       [0.7462439 , 0.18532327, 0.48359504, 0.31681307],
       [0.50229437, 0.18910139, 0.20765138, 0.74078064]])

In [372]:
# Array of random numbers between 0 and 1
arr = np.random.rand(2, 3)

In [373]:
arr

array([[0.08671603, 0.40946921, 0.41317455],
       [0.20087297, 0.72518644, 0.51321783]])

In [370]:
# random number between an interval
arr = np.random.randint(1, 15, (3, 4))

In [371]:
arr

array([[10,  3,  5,  6],
       [11,  9,  7,  6],
       [12,  3,  7, 11]])

How to subset rows and columns in dataset?

Using Numpy

In [376]:
data = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

In [377]:
data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [378]:
# Subsetting Rows
# 1st and 3rd row
subset_rows = data[[0, 2], : ]

In [379]:
subset_rows

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [380]:
# subsetting columns
# 2nd and 4th column
subset_cols = data[: , [1,3] ]

In [375]:
subset_cols

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [330]:
# subsetting rows and columns simultaneously
subset = data[[0, 2], :][:, [1, 3]]

In [331]:
subset

array([[ 2,  4],
       [10, 12]])

Using Pandas

In [332]:
data = pd.DataFrame(
    { 'A' : [1, 5, 9, 3],
     'B' : [2, 6, 10, 4],
     'C' : [3, 7, 11, 15],
     'D' : [4, 8, 12, 16]
    }
)

In [333]:
data

A   B   C   D
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12
3  3   4  15  16

In [336]:
# Subsetting Rows
data.iloc[[0, 2]]

A   B   C   D
0  1   2   3   4
2  9  10  11  12

In [344]:
# Select rows where column 'A' is greater than 5
data[data['A'] > 5]

A   B   C   D
2  9  10  11  12

In [351]:
# Subsetting Columns
data[['B', 'D']]

B   D
0   2   4
1   6   8
2  10  12
3   4  16

In [352]:
data

A   B   C   D
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12
3  3   4  15  16

In [353]:
# subsetting rows and columns
# subsetting 1st and 3rd row, B and D column
subset = data.loc[[0, 2], ['B', 'D']]

In [354]:
subset

B   D
0   2   4
2  10  12

Pandas functions

In [357]:
# DataFrame Creation
data = {'A': [1, 2, 3], 'B' : [4, 5, 6] }
df = pd.DataFrame(data)

In [358]:
df

A  B
0  1  4
1  2  5
2  3  6

Basic Operations

Viewing Data

In [359]:
df.head()

A  B
0  1  4
1  2  5
2  3  6

In [360]:
df.tail()

A  B
0  1  4
1  2  5
2  3  6

In [361]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes


In [362]:
df.describe()

A    B
count  3.0  3.0
mean   2.0  5.0
std    1.0  1.0
min    1.0  4.0
25%    1.5  4.5
50%    2.0  5.0
75%    2.5  5.5
max    3.0  6.0

2. Accessing Data

In [364]:
# column A
df['A']

0    1
1    2
2    3
Name: A, dtype: int64

In [366]:
# column A and B
df[['A', 'B']]

A  B
0  1  4
1  2  5
2  3  6

In [382]:
# 1st row
df.loc[0]

A    1
B    4
Name: 0, dtype: int64

In [368]:
df.iloc[0]

A    1
B    4
Name: 0, dtype: int64

In [369]:
df.loc[0, 'A']

1

Data Manipulation

In [383]:
# 1. Filtering Data
df[df['A'] > 1]

A  B
1  2  5
2  3  6

In [392]:
# 2.Adding/Removing Columns
df['C'] = df['A'] + df['B']

In [393]:
df

A  B  C
0  1  4  5
1  2  5  7
2  3  6  9

In [406]:
df.drop('C', axis = 1, inplace = True)

In [407]:
df

Alpha  Beta
0      1     4
1      2     5
2      3     6

In [400]:
# 3. Renaming Columns
df.rename(columns = {'A' : 'Alpha', 'B' : 'Beta' }, inplace = True)

In [404]:
df

Alpha  Beta  C
0      1     4  5
1      2     5  7
2      3     6  9

In [411]:
# 4. Sorting Data
df.sort_values(by='Alpha', ascending = False, inplace = True )

In [412]:
df

Alpha  Beta
2      3     6
1      2     5
0      1     4